"""empty message

Revision ID: cb44825fcc1f
Revises: e5e01ccefdf7
Create Date: 2024-11-22 19:08:45.369101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb44825fcc1f'
down_revision = 'e5e01ccefdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme_image_link', sa.String(length=50), nullable=True))
        batch_op.drop_column('them_image_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.add_column(sa.Column('them_image_link', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('theme_image_link')

    # ### end Alembic commands ###
