"""empty message

Revision ID: ce9d054a0116
Revises: cb44825fcc1f
Create Date: 2024-11-22 19:29:25.987100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9d054a0116'
down_revision = 'cb44825fcc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
